FROM php:{{ .PHPVersion }}-fpm

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    curl \
    libzip-dev \
    libicu-dev \
    libxml2-dev \
    libpq-dev \
    && docker-php-ext-install \
    pdo_mysql \
    mysqli \
{{- if eq .Database "postgres" }}
    pdo_pgsql \
{{- end }}
    zip \
    intl \
    opcache

COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

WORKDIR /var/www/html